prompt -- QUESTION 8;
SELECT TABLE_NAME FROM USER_TABLES;

prompt -- QUESTION 9 (peut pas la faire);

prompt -- QUESTION 10;
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ABONNE';

prompt -- QUESTION 11;
SELECT COUNT(COLUMN_NAME) FROM USER_TAB_COLUMNS;

prompt -- QUESTION 12;
SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME LIKE 'PK%' OR CONSTRAINT_NAME LIKE 'FK%';